{
 "title": "Fastfood Tech Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total de Pedidos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (fastfood_orders_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS por Rota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(route) (rate(fastfood_http_request_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(fastfood_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}